name: Install macOS pkg Action
author: joncrain
description: GitHub Action to install a macOS package on the runner.

branding:
  icon: command
  color: gray-dark

inputs:
  pkg_url:
    required: true
    description: URL to the pkg to download and install.

runs:
  using: "composite"
  steps:
    - name: Download pkg
      id: download
      run: |
        /usr/bin/curl ${{ inputs.pkg_url }} -o /tmp/installer.pkg
      shell: bash
    - name: Install pkg
      id: install
      run: |
        /usr/sbin/installer -pkg /tmp/installer.pkg -target /
      shell: bash
